apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service-srdc
  namespace: nimble-platform
  labels:
    app: nimble-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service-srdc
  template:
    metadata:
      labels:
        app: catalog-service-srdc
    spec:
      containers:
        - name: catalog-service-srdc
          image: 'rannybal2024/catalog-service:IMAGE_TAG'
          ports:
            - containerPort: 8095
              protocol: TCP
          env:
            - name: CATALOGUE_SERVICE_URL
            - name: INDEXING_SERVICE_URL
              value: 'http://indexing-service:8080/'
            - name: CATALOG_SERVICE_OAUTH_CLIENT_ID
              value: catalog-service-srdc-client
            - name: CATALOG_SERVICE_OAUTH_SECRET
              value: 3ee23df3-9a8b-4edb-aac1-faf5017cda2d
            - name: OAUTH_CLIENT_ACCESSTOKEN_URI
              value: >-
                http://keycloak:8080/auth/realms/master/protocol/openid-connect/token
            - name: CATEGORY_DB_HOST
              value: kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com
            - name: CATEGORY_DB_PORT
              value: '25060'
            - name: CATEGORY_DB_NAME
              value: catalogdb?ssl=true&sslmode=require
            - name: CATEGORY_DB_USERNAME
              value: doadmin
            - name: CATEGORY_DB_PASSWORD
              value: AVNS_xN6h3TZAvlOwe4vdAdk
            - name: UBL_DB_HOST
              value: kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com
            - name: UBL_DB_HOST_PORT
              value: '25060'
            - name: UBL_DB_NAME
              value: ubldb
            - name: UBL_DB_PARAMS
              value: '&ssl=true&sslmode=require'
            - name: UBL_DB_USERNAME
              value: doadmin
            - name: UBL_DB_PASSWORD
              value: AVNS_xN6h3TZAvlOwe4vdAdk
            - name: CATALOGUE_SERVICE_ENABLED_TAXONOMIES
              value: 'eClass,FurnitureOntology'
            - name: CAMUNDA_DB_HOST
              value: kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com
            - name: CAMUNDA_DB_PORT
              value: '25060'
            - name: CAMUNDA_DB_NAME
              value: camundadb
            - name: CAMUNDA_DB_USERNAME
              value: doadmin
            - name: CAMUNDA_DB_PASSWORD
              value: AVNS_xN6h3TZAvlOwe4vdAdk
            - name: BINARY_CONTENT_DB_HOST
              value: kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com
            - name: BINARY_CONTENT_DB_PORT
              value: '25060'
            - name: BINARY_CONTENT_DB_NAME
              value: binarycontentdb
            - name: BINARY_CONTENT_DB_PARAMS
              value: '&ssl=true&sslmode=require'
            - name: BINARY_CONTENT_DB_USERNAME
              value: doadmin
            - name: BINARY_CONTENT_DB_PASSWORD
              value: AVNS_xN6h3TZAvlOwe4vdAdk
            - name: BINARY_CONTENT_URL
              value: 'http://not-yet-in-use/'
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: 'kafka:9092'
            - name: KAFKA_JAAS_CONFIG
            - name: _JAVA_OPTIONS
              value: '-Xmx512m -Xms50m'
            - name: SMTP_HOST
              value: maildev
            - name: SMTP_PORT
              value: '25'
            - name: SMTP_DEFAULT_FROM
              value: nimble@local-dev
            - name: SMTP_USERNAME
            - name: SMTP_PASSWORD
            - name: SMTP_AUTH
              value: 'false'
            - name: SMTP_STARTTLS
              value: 'false'
            - name: BP_SERVICE_OAUTH_CLIENT_ID
              value: bp-service-client
            - name: BP_SERVICE_OAUTH_SECRET
              value: 9570fee1-f7a2-4922-890d-5f48cb4664c4
            - name: IDENTITY_SERVICE_URL
              value: 'http://identity-service:9096/'
            - name: TRUST_SERVICE_URL
              value: 'http://trust-service:9098/'
            - name: CONFIG_SERVER_URI
              value: 'http://config-server:8888'
            - name: CONFIG_SERVER_FAILFAST
              value: 'true'
            - name: DISCOVERY_ENABLED
              value: 'true'
            - name: EUREKA_CLIENT_HEALTHCHECK
              value: 'false'
            - name: DISCOVERY_PREFER_IP
              value: 'false'
            - name: DISCOVERY_SERVER_URI
              value: 'http://service-discovery:8761'
            - name: BUSINESS_PROCESS_SERVICE_URL
            - name: DATA_CHANNEL_SERVICE_URL
              value: 'http://data-channel-service:9099'
            - name: FRONTEND_URL
              value: 'https://nimble.kolayam.co.uk'
            - name: FEDERATION_INSTANCE_ID
            - name: KAFKA_TOPIC_BUSINESS_PROCESS_UPDATES
            - name: KEYCLOAK_PUBLIC_KEY
              value: >-
                MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg99CjKcp4Lm28juVmoe8nitA4yRdDOvQO5kzhPmUCSut9yyAYlJt9JNOFJMRs3zJoEd2JzpI9gBrQYWAQ8q/Uf13lQHDYPQATBdGt+eI7a0Cxl/NGRAOap56yg1KwWs89EIaTiAdQNiWLWXUAm5xA6MGEevBj/azbMofBpf4wjtJ6bFAEa5KGrfEuzMTxiWHNiM8F0ow17STJx5s/T+wqw6qZ+pK6pE1DvbZ0KDOyLCwBvYAMwd7tw5jmSjMnlOn3k1SoCDv9kt8/UL6AJMXMTQZFsyPuthPA/XidRlJCRGaoiNByfSoQExtlO5PkFeDy1vBsqRTL3cpIbVeDsP+JQIDAQAB
          resources:
            limits:
              memory: 2000Mi
            requests:
              cpu: 200m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
