apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service-srdc
  namespace: nimble-platform
  labels:
    app: nimble-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service-srdc
  template:
    metadata:
      labels:
        app: catalog-service-srdc
    spec:
      containers:
        - name: catalog-service-srdc
          image: 'rannybal2024/catalog-service:IMAGE_TAG'
          ports:
            - containerPort: 8095
              protocol: TCP
          env:
            - name: CATALOGUE_SERVICE_URL
            - name: INDEXING_SERVICE_URL
              value: 'http://indexing-service:8080/'
            - name: CATALOG_SERVICE_OAUTH_CLIENT_ID
              value: catalog-service-client
            - name: CATALOG_SERVICE_OAUTH_SECRET
              value: 09eae741-0684-4798-b728-aa6a8e59ca71
            - name: OAUTH_CLIENT_ACCESSTOKEN_URI
              value: >-
                http://keycloak:8080/auth/realms/master/protocol/openid-connect/token
            - name: CATEGORY_DB_HOST
              value: kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com
            - name: CATEGORY_DB_PORT
              value: '25060'
            - name: CATEGORY_DB_NAME
              value: catalogdb?ssl=true&sslmode=require
            - name: CATEGORY_DB_USERNAME
              value: doadmin
            - name: CATEGORY_DB_PASSWORD
              value: AVNS_xN6h3TZAvlOwe4vdAdk
            - name: UBL_DB_HOST
              value: kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com
            - name: UBL_DB_HOST_PORT
              value: '25060'
            - name: UBL_DB_NAME
              value: ubldb
            - name: UBL_DB_PARAMS
              value: '&ssl=true&sslmode=require'
            - name: UBL_DB_USERNAME
              value: doadmin
            - name: UBL_DB_PASSWORD
              value: AVNS_xN6h3TZAvlOwe4vdAdk
            - name: CATALOGUE_SERVICE_ENABLED_TAXONOMIES
              value: 'eClass,FurnitureOntology'
            - name: CAMUNDA_DB_HOST
              value: kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com
            - name: CAMUNDA_DB_PORT
              value: '25060'
            - name: CAMUNDA_DB_NAME
              value: camundadb
            - name: CAMUNDA_DB_USERNAME
              value: doadmin
            - name: CAMUNDA_DB_PASSWORD
              value: AVNS_xN6h3TZAvlOwe4vdAdk
            - name: BINARY_CONTENT_DB_HOST
              value: kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com
            - name: BINARY_CONTENT_DB_PORT
              value: '25060'
            - name: BINARY_CONTENT_DB_NAME
              value: binarycontentdb
            - name: BINARY_CONTENT_DB_PARAMS
              value: '&ssl=true&sslmode=require'
            - name: BINARY_CONTENT_DB_USERNAME
              value: doadmin
            - name: BINARY_CONTENT_DB_PASSWORD
              value: AVNS_xN6h3TZAvlOwe4vdAdk
            - name: BINARY_CONTENT_URL
              value: 'http://not-yet-in-use/'
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: 'kafka:9092'
            - name: KAFKA_JAAS_CONFIG
            - name: _JAVA_OPTIONS
              value: '-Xmx512m -Xms50m'
            - name: SMTP_HOST
              value: maildev
            - name: SMTP_PORT
              value: '25'
            - name: SMTP_DEFAULT_FROM
              value: nimble@local-dev
            - name: SMTP_USERNAME
            - name: SMTP_PASSWORD
            - name: SMTP_AUTH
              value: 'false'
            - name: SMTP_STARTTLS
              value: 'false'
            - name: BP_SERVICE_OAUTH_CLIENT_ID
              value: bp-service-client
            - name: BP_SERVICE_OAUTH_SECRET
              value: 621c1ec2-6753-4ead-925f-a5df24876a2b
            - name: IDENTITY_SERVICE_URL
              value: 'http://identity-service:9096/'
            - name: TRUST_SERVICE_URL
              value: 'http://trust-service:9098/'
            - name: CONFIG_SERVER_URI
              value: 'http://config-server:8888'
            - name: CONFIG_SERVER_FAILFAST
              value: 'true'
            - name: DISCOVERY_ENABLED
              value: 'true'
            - name: EUREKA_CLIENT_HEALTHCHECK
              value: 'false'
            - name: DISCOVERY_PREFER_IP
              value: 'false'
            - name: DISCOVERY_SERVER_URI
              value: 'http://service-discovery:8761'
            - name: BUSINESS_PROCESS_SERVICE_URL
            - name: DATA_CHANNEL_SERVICE_URL
              value: 'http://data-channel-service:9099'
            - name: FRONTEND_URL
              value: 'https://nimble.kolayam.co.uk'
            - name: FEDERATION_INSTANCE_ID
            - name: KAFKA_TOPIC_BUSINESS_PROCESS_UPDATES
            - name: KEYCLOAK_PUBLIC_KEY
              value: "-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjbTzPIh+ff5lTVW0c4veuS3Ers+29+h9mXXcwkojaDRwzHmf1ZCVvJY3eNy6NCu0SwVksA2tusBZK+qiSo4Kk24DDTNz1JQ7HDvXzTxH6Vfz8vPC9qq+kOPBqUOXctlNTiyz+8uEA6rS1ZpzcbVOdds0xx9k0pSlZhXxbeJlq+m8nS5cWNiAMnS4Z0UQDJXNL5Y8a4z8XTPlX5cv9B2cikQpQ97grnUQ1ihAs+7gw6Jo1DyU+6V1KEYK89yPtn8bSvsgVSIx0g97kBS7c2EhmqBgQ5h5zXW7nLXTiNE+va7Gk0Bfaf6jw5j8p5/uigrRlmgoTQxvgE7oiviJA18ZTQIDAQAB-----END PUBLIC KEY-----"
          resources:
            limits:
              memory: 2000Mi
            requests:
              cpu: 200m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
