apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service-srdc
  namespace: nimble-platform
  labels:
    app: nimble-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service-srdc
  template:
    metadata:
      labels:
        app: catalog-service-srdc
    spec:
      containers:
        - name: catalog-service-srdc
          image: 'rannybal2024/catalog-service:IMAGE_TAG'
          ports:
            - containerPort: 8095
              protocol: TCP
          env:
            - name: HMRC_API_BASE
              value: 'https://api.service.hmrc.gov.uk'
            - name: HMRC_CLIENT_ID
              value: 'jdasIzzRLEfbF1q2avZNzihifonz'
            - name: HMRC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: HMRC_CLIENT_SECRET
            - name: CATALOGUE_SERVICE_URL
            - name: INDEXING_SERVICE_URL
              value: 'http://indexing-service:8080/'
            - name: CATALOG_SERVICE_OAUTH_CLIENT_ID
              value: catalog-service-client
            - name: CATALOG_SERVICE_OAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: CATALOG_SERVICE_OAUTH_SECRET
            - name: OAUTH_CLIENT_ACCESSTOKEN_URI
              value: >-
                http://keycloak:8080/auth/realms/master/protocol/openid-connect/token
            - name: CATEGORY_DB_HOST
              value: kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com
            - name: CATEGORY_DB_PORT
              value: '25061'
            - name: CATEGORY_DB_NAME
              value: catalogdb?ssl=true&sslmode=require
            - name: CATEGORY_DB_USERNAME
              value: doadmin
            - name: CATEGORY_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: PG_DOADMIN_PASSWORD
            - name: UBL_DB_HOST
              value: kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com
            - name: UBL_DB_HOST_PORT
              value: '25061'
            - name: UBL_DB_NAME
              value: ubldb
            - name: UBL_DB_PARAMS
              value: '&ssl=true&sslmode=require'
            - name: UBL_DB_USERNAME
              value: doadmin
            - name: UBL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: PG_DOADMIN_PASSWORD
            - name: CATALOGUE_SERVICE_ENABLED_TAXONOMIES
              value: 'eClass,FurnitureOntology'
            - name: CAMUNDA_DB_HOST
              value: kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com
            - name: CAMUNDA_DB_PORT
              value: '25061'
            - name: CAMUNDA_DB_NAME
              value: camundadb
            - name: CAMUNDA_DB_USERNAME
              value: doadmin
            - name: CAMUNDA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: PG_DOADMIN_PASSWORD
            - name: BINARY_CONTENT_DB_HOST
              value: kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com
            - name: BINARY_CONTENT_DB_PORT
              value: '25061'
            - name: BINARY_CONTENT_DB_NAME
              value: binarycontentdb
            - name: BINARY_CONTENT_DB_PARAMS
              value: '&ssl=true&sslmode=require'
            - name: BINARY_CONTENT_DB_USERNAME
              value: doadmin
            - name: BINARY_CONTENT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: PG_DOADMIN_PASSWORD
            - name: BINARY_CONTENT_URL
              value: 'http://not-yet-in-use/'
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: 'kafka:9092'
            - name: KAFKA_JAAS_CONFIG
            - name: _JAVA_OPTIONS
              value: '-Xmx1024m -Xms50m'
            - name: SMTP_HOST
              value: "smtp.gmail.com"
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_DEFAULT_FROM
              value: "support@kolanot.co.uk"
            - name: SMTP_USERNAME
              value: "support@kolanot.co.uk"
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: SMTP_PASSWORD
            - name: SMTP_AUTH
              value: "true"
            - name: SMTP_STARTTLS
              value: "true"
            - name: LOGSTASH_URI
              value: "logstash-service:5044"
            - name: BP_SERVICE_OAUTH_CLIENT_ID
              value: bp-service-client
            - name: BP_SERVICE_OAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: BP_SERVICE_OAUTH_SECRET
            - name: IDENTITY_SERVICE_URL
              value: 'http://identity-service:9096/'
            - name: TRUST_SERVICE_URL
              value: 'http://trust-service:9098/'
            - name: CONFIG_SERVER_URI
              value: 'http://config-server:8888'
            - name: CONFIG_SERVER_FAILFAST
              value: 'true'
            - name: DISCOVERY_ENABLED
              value: 'true'
            - name: EUREKA_CLIENT_HEALTHCHECK
              value: 'false'
            - name: DISCOVERY_PREFER_IP
              value: 'false'
            - name: DISCOVERY_SERVER_URI
              value: 'http://service-discovery:8761'
            - name: BUSINESS_PROCESS_SERVICE_URL
            - name: DATA_CHANNEL_SERVICE_URL
              value: 'http://data-channel-service:9099'
            - name: FRONTEND_URL
              value: 'https://nimble.kolayam.co.uk'
            - name: FEDERATION_INSTANCE_ID
              value: "kerberos"
            - name: DELEGATE_SERVICE_URL
              value: "http://delegate-service:8080"
            - name: KAFKA_TOPIC_BUSINESS_PROCESS_UPDATES
            - name: KEYCLOAK_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: KEYCLOAK_PUBLIC_KEY
          resources:
            limits:
              memory: 2000Mi
            requests:
              cpu: 200m
              memory: 256Mi
      dnsPolicy: ClusterFirst
